export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEES";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEES";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEES";
